Repository Mathieu-Lala/Kawaii_Engine, pull requests merged in 2021-06, with the labels that each got.

#14 Feature/model loader#2
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/resources/Model.hpp
  src/KawaiiEngine/include/resources/ResourceLoader.hpp
  src/KawaiiEngine/include/resources/Texture.hpp
  src/KawaiiEngine/main.cpp
Labels: enhancement :sparkles:

#13 feat: add gravity / velocity
  conanfile.txt
  src/KawaiiEngine/CMakeLists.txt
  src/KawaiiEngine/asset/models/viking_room.obj
  src/KawaiiEngine/asset/textures/viking_room.png
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/main.cpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: enhancement :sparkles:

#16 Edit/mesh path
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: enhancement :sparkles:

#20 refact: clean a bit engine
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/resources/Model.hpp
  src/KawaiiEngine/include/resources/ResourceLoader.hpp
  src/KawaiiEngine/include/resources/Texture.hpp
Labels: proposition :question:

#22 Feat/collision
  src/KawaiiEngine/include/Camera.hpp
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: bug :ambulance:, enhancement :sparkles:

#23 Feat/entity tree
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/widgets/EntityHierarchy.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: bug :ambulance:, enhancement :sparkles:

#24 Feature: adding multiple camera
  src/KawaiiEngine/include/Camera.hpp
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/graphics/Window.hpp
  src/KawaiiEngine/include/helpers/Rectangle.hpp
  src/KawaiiEngine/src/EventProvider.cpp
  src/KawaiiEngine/src/graphics/Window.cpp
Labels: bug :ambulance:, enhancement :sparkles:, proposition :question:

#28 Feature/shader loader#15
  src/KawaiiEngine/asset/shader/default.frag
  src/KawaiiEngine/asset/shader/default.vert
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/graphics/Shader.hpp
  src/KawaiiEngine/include/resources/ResourceLoader.hpp
  src/KawaiiEngine/src/graphics/Shader.cpp
  src/KawaiiEngine/src/resources/ResourceLoader.cpp
Labels: enhancement :sparkles:

#37 Feature/primitives
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/primitives/Line.hpp
  src/KawaiiEngine/include/primitives/Sphere.hpp
  src/KawaiiEngine/include/resources/ResourceLoader.hpp
Labels: enhancement :sparkles:

#39 feat: add inspector for texture
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: enhancement :sparkles:

#40 feat: add shader normals
  LICENSE
  src/KawaiiEngine/asset/shader/normal.frag
  src/KawaiiEngine/asset/shader/normal.vert
  src/KawaiiEngine/include/State.hpp
Labels: enhancement :sparkles:

#41 feat: add broken pick object
  src/KawaiiEngine/asset/shader/picking.frag
  src/KawaiiEngine/asset/shader/picking.vert
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/src/graphics/Shader.cpp
Labels: bug :ambulance:, enhancement :sparkles:

#42 feat: add camera as entity
  src/KawaiiEngine/include/Camera.hpp
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: bug :ambulance:, enhancement :sparkles:

#43 Feature/component clock#38
  src/KawaiiEngine/include/component.hpp
Labels: enhancement :sparkles:

#51 Port/windows
  .github/workflows/cmake-debug.yaml
  .gitignore
  doc/screenshot/screenshot_2021-06-17_13-01-54.png
  requirements.py
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/graphics/Shader.hpp
  src/KawaiiEngine/include/graphics/Window.hpp
  src/KawaiiEngine/src/graphics/Window.cpp
Labels: documentation, enhancement :sparkles:

#56 :sparkles: emplacing parent component on all entity's children when c…
  src/KawaiiEngine/include/component.hpp
Labels: enhancement :sparkles:

#57 Feature/enable internal gui
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/State.hpp
Labels: enhancement :sparkles:

#58 Fix/picking
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/widgets/ComponentInspector.hpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: enhancement :sparkles:

#60 Tweak
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/resources/ResourceLoader.hpp
  src/KawaiiEngine/include/widgets/EventMonitor.hpp
Labels: enhancement :sparkles:

#62 Fix/build windows
  src/KawaiiEngine/CMakeLists.txt
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/widgets/ComponentInspector.hpp
  src/KawaiiEngine/src/Engine.cpp
  src/KawaiiEngine/src/widgets/ComponentInspector.cpp
Labels: enhancement :sparkles:

#63 fix: reduce size of time elapsed serialisation
  src/KawaiiEngine/asset/models/uploads_files_896621_solarsystem.c4d
  src/KawaiiEngine/asset/models/uploads_files_896621_solarsystem.mtl
  src/KawaiiEngine/asset/models/uploads_files_896621_solarsystem.obj
  src/KawaiiEngine/include/Context.hpp
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/Event.hpp
  src/KawaiiEngine/include/EventProvider.hpp
  src/KawaiiEngine/include/component.hpp
  src/KawaiiEngine/include/widgets/ComponentInspector.hpp
  src/KawaiiEngine/include/widgets/EventMonitor.hpp
  src/KawaiiEngine/src/Engine.cpp
  src/KawaiiEngine/src/EventProvider.cpp
Labels: enhancement :sparkles:

#64 feat: add more glfw window event; + export on close event provider
  README.md
  cmake/Conan.cmake
  src/KawaiiEngine/include/Event.hpp
  src/KawaiiEngine/include/EventProvider.hpp
  src/KawaiiEngine/include/graphics/Window.hpp
  src/KawaiiEngine/include/widgets/EventMonitor.hpp
  src/KawaiiEngine/src/Engine.cpp
  src/KawaiiEngine/src/EventProvider.cpp
  src/KawaiiEngine/src/graphics/Window.cpp
  tests/golden_test/take_one_screenshot.json
  tests/golden_test/todo
Labels: enhancement :sparkles:

#66 Feat/console
  src/KawaiiEngine/include/Engine.hpp
  src/KawaiiEngine/include/widgets/Console.hpp
  src/KawaiiEngine/src/Engine.cpp
Labels: enhancement :sparkles:
